site_name: "BigCommerce Theme Supermarket - User Guide"
pages:
- Home: index.md
- Install the theme: installation.md
- Quick Start Guide: quickstart.md
- Customization: customization.md
- Help & Support: support.md
theme: readthedocs
use_directory_urls: false

extra_css:
  - https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
  - css/style.css
extra_javascript:
  - https://use.fontawesome.com/540034d990.js

markdown_extensions:
- toc:
    permalink: True
    separator: "-"
- sane_lists
- extra
- fenced_code

google_analytics: ['UA-241859-16', 'tvlgiao.github.io']